### ISSUE TITLE
Missing documents 

### ISSUE THREAD

**Issue by Jbutler-helpful** [nycmeshnet/docs#123]
I am interested in seeing org documents defining the structure of the entity

**Comment by bhny** [comment]
what specifically do you mean? organization structure or network structure?

**Comment by fabacab** [comment]
> I am interested in seeing org documents defining the structure of the entity

@Jbutler-helpful For what it's worth, there are many (many) expanded documents and explanations on my fork of these docs available at https://nycmesh-docs.netlify.app/ that might provide more of the information you're looking for, depending on what you mean by "structure of the entity"?
