### ISSUE TITLE
Broken link to LAP-120

### ISSUE THREAD

**Issue by WesleyAC** [nycmeshnet/docs#74]
The link on https://docs.nycmesh.net/hardware/liteap/ is broken. It seems like maybe ubiquity stopped setting these? As far as I can tell, https://www.ui.com/airmax/liteap-ac/ is the closest page, but that only has a link to buy the LAP-GPS version (which is 90°, instead of 120°).

Anyway, we should probably link to something that isn't broken :)

**Comment by OlivierMorf** [comment]
Fixed
